baseurl = "https://akdillon.net"
languageCode = "en-us"
title = "AKDillon"
canonifyurls = true
SectionPagesMenu = "main"

[[menu.main]]
    name = "Home"
    weight = 0
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "Audio"
    weight = 50
    identifier = "audio"
    url = "/audio/"

[[menu.main]]
    name = "About"
    weight = 100
    identifier = "about"
    url = "/about/"

[[menu.main]]
    name = "Contact"
    weight = 150
    identifier = "contact"
    url = "/contact/"
