baseurl = "http://www.akdillon.net"
languageCode = "en-us"
title = "AKDillon"
canonifyurls = true

[[menu.main]]
    name = "Misc"
    weight = -20
    identifier = "misc"
    url = "/misc/"

[[menu.main]]
    name = "About"
    weight = -10
    identifier = "about"
    url = "/about/"

[[menu.main]]
    name = "Contact"
    weight = 0
    identifier = "contact"
    url = "/contact/"

[params]
copyrightyear = "2015"
