baseurl = "http://www.akdillon.net"
languageCode = "en-us"
title = "AKDillon"
canonifyurls = true

[[menu.main]]
    name = "MRD CE Thesis"
    weight = -30
    identifier = "mrd_ce_thesis"
    url = "/mrd_ce_thesis/"

[[menu.main]]
    name = "Audio"
    weight = -20
    identifier = "audio"
    url = "/audio/"

[[menu.main]]
    name = "About"
    weight = -10
    identifier = "about"
    url = "/about/"

[[menu.main]]
    name = "Contact"
    weight = 0
    identifier = "contact"
    url = "/contact/"

[params]
copyrightyear = "2015"
